FROM alpine:3.3
MAINTAINER Jan Broer <jan@festplatte.eu.org>

RUN apk add --no-cache ca-certificates

ADD build/rancher-letsencrypt-linux-amd64 /usr/bin/rancher-letsencrypt
RUN chmod +x /usr/bin/rancher-letsencrypt

VOLUME /etc/letsencrypt

ENTRYPOINT ["/usr/bin/rancher-letsencrypt"]